services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - frontend
    networks:
      - app-network
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
